# Install script for directory: /home/pi/opencv-3.0.0/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "RELEASE")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/pi/opencv-3.0.0/cmake/modules/calib3d/.calib3d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/core/.core/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudaarithm/.cudaarithm/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudabgsegm/.cudabgsegm/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudacodec/.cudacodec/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudafeatures2d/.cudafeatures2d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudafilters/.cudafilters/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudaimgproc/.cudaimgproc/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudalegacy/.cudalegacy/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudaobjdetect/.cudaobjdetect/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudaoptflow/.cudaoptflow/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudastereo/.cudastereo/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudawarping/.cudawarping/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cudev/.cudev/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/features2d/.features2d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/flann/.flann/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/hal/.hal/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/highgui/.highgui/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/imgcodecs/.imgcodecs/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/imgproc/.imgproc/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/java/.java/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ml/.ml/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/objdetect/.objdetect/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/photo/.photo/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/python/.python/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/shape/.shape/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/stitching/.stitching/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/superres/.superres/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ts/.ts/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/video/.video/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/videoio/.videoio/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/videostab/.videostab/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/viz/.viz/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/world/.world/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/adas/.adas/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/bgsegm/.bgsegm/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/bioinspired/.bioinspired/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ccalib/.ccalib/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/contrib_world/.contrib_world/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/cvv/.cvv/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/datasets/.datasets/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/face/.face/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/latentsvm/.latentsvm/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/line_descriptor/.line_descriptor/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/matlab/.matlab/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/optflow/.optflow/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/reg/.reg/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/rgbd/.rgbd/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/saliency/.saliency/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/surface_matching/.surface_matching/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/text/.text/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/tracking/.tracking/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/xfeatures2d/.xfeatures2d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ximgproc/.ximgproc/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/xobjdetect/.xobjdetect/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/xphoto/.xphoto/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/hal/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/core/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/flann/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/imgproc/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ml/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/photo/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/reg/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/surface_matching/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/video/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/face/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/imgcodecs/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/shape/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/videoio/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/highgui/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/objdetect/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/optflow/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/superres/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/tracking/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ts/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ximgproc/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/xobjdetect/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/xphoto/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/adas/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/bgsegm/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/bioinspired/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/features2d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/latentsvm/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/line_descriptor/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/saliency/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/text/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/calib3d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/ccalib/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/datasets/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/rgbd/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/videostab/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/xfeatures2d/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/stitching/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/python2/cmake_install.cmake")
  include("/home/pi/opencv-3.0.0/cmake/modules/python3/cmake_install.cmake")

endif()

